//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientApplication.UtilitySvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UtilitySvc.IUtilityService")]
    public interface IUtilityService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilityService/GetData", ReplyAction="http://tempuri.org/IUtilityService/GetDataResponse")]
        string GetData(int i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilityService/GetData", ReplyAction="http://tempuri.org/IUtilityService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int i);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUtilityServiceChannel : ClientApplication.UtilitySvc.IUtilityService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UtilityServiceClient : System.ServiceModel.ClientBase<ClientApplication.UtilitySvc.IUtilityService>, ClientApplication.UtilitySvc.IUtilityService {
        
        public UtilityServiceClient() {
        }
        
        public UtilityServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UtilityServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UtilityServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UtilityServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int i) {
            return base.Channel.GetData(i);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int i) {
            return base.Channel.GetDataAsync(i);
        }
    }
}
